version: "3"

services:
  hub:
    image: selenium/hub:3.141
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1
