version: "3"

services:
  hub:
    image: selenium/hub:4.1.1-20211217
    ports:
      - "4444:4444"
#    environment:

  chrome:
    image: selenium/node-chrome:96.0
    depends_on:
      - hub
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 1
      SE_NODE_SESSION_TIMEOUT: 60

  chrome2:
    image: selenium/node-chrome:94.0
    depends_on:
      - hub
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 1
      SE_NODE_SESSION_TIMEOUT: 60
